version: "3.8"

services:
  vacapp-backend:
    build:
      context: ./backend
    container_name: vacapp-backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - vacapp-db
  vacapp-web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    container_name: vacapp-web
    restart: unless-stopped
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 4000:4000
  vacapp-db:
    image: "postgres:16.2-alpine"
    container_name: vacapp-db
    restart: unless-stopped
    volumes:
      - vacapp-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  vacapp-data:
    driver: local
